### ISSUE TITLE
Where can we find documentation on testing plugins?

### ISSUE THREAD

**Issue by fransflippo** [amphro/streamer#2]
Hi!

I'm trying to write my own plugin and have proper tests for it, but I'm finding it SO hard to find some documentation on writing these tests.

What doesn't help is that everyone seems to be doing it differently, and it would be nice if there was one "Best Practice" way.

Where I've looked:

- The generated test class when you generate a new plugin with sfdx
- The Salesforce documentation at https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_test.htm -- they don't really say a lot here but refer to cli-plugins-testkit at https://github.com/salesforcecli/cli-plugins-testkit/blob/main/SAMPLES.md
- The **cli-plugins-testkit**
- The streamer plugin (this repository)
- Shane McLaughlin's plugin at https://github.com/mshanemc/shane-sfdx-plugins

### The generated test class

Generate test class uses `@salesforce/command/lib/test` to run the plugin on an org:
```
    describe('hello:org', () => {
      test
        .withOrg({ username: 'test@org.com' }, true)
        .withConnectionRequest(request => {
          const requestMap = ensureJsonMap(request);
          if (ensureString(requestMap.url).match(/Organization/)) {
            return Promise.resolve({ records: [ { Name: 'Super Awesome Org', TrialExpirationDate: '2018-03-20T23:24:11.000+0000'}] });
          }
          return Promise.resolve({ records: [] });
        })
        .stdout()
        .command(['hello:org', '--targetusername', 'test@org.com'])
        .it('runs hello:org --targetusername test@org.com', ctx => {
          expect(ctx.stdout).to.contain('Hello world! This is org: Super Awesome Org and I will be around until Tue Mar 20 2018!');
        });
    });
```

What's not entire clear to me is whether this `withOrg` is a real org created on the fly, or an "in-memory" org maybe, or something else? Also, if it is a real org, how is it created? What kind of org is it? Is it automatically destroyed at the end of the test? 

I also can't tell from the generated code how I would mock out dependencies that I've already tested separately.

### The Salesforce documentation

Well, "documentation" is really too much credit for what's just two paragraphs:

> While you’re coding and customizing your plug-in, be sure to write associated tests for each new feature to ensure that it’s working as you expect. In your test suites, include both unit tests and more complex integration, smoke, and end-to-end tests. To help you with latter, we’ve created a library of testing utilities that you add to your environment as a Yarn developer dependency.
> To help you get started, we provide descriptions of common use cases and associated sample testing code. And we link to other public GitHub repos that use the library so you can see the testing utilities in action. Check out all the code and documentation in the [cli-plugins-testkit](https://github.com/salesforcecli/cli-plugins-testkit/blob/main/SAMPLES.md) GitHub repo.

I've looked at the examples in the **cli-plugins-testkit**. There are a lot of examples, but again I really can't figure out what it is they do. Which takes me to the next point.

### The **cli-plugins-testkit**

There's mention of `TestSession`s but it doesn't say what they are -- are they connections to an org? How are they different then from "real" connections? Again, is this a test org created just for the duration of the test or is it an org I must have created beforehand? (If so, how does it authenticate?)

How would I actually mock out the connection altogether if I don't want to run my test against a real org but rather fake/stub the org's behavior in my test?

How do I stub other dependencies/helpers that my plugin uses?

### The streamer plugin (this repository)

The presentation in the repo says "Break out code into files that the command calls - This helps with mocking out calls, especially calls to core/command" - but I don't see an example of this; there's just a single `stream.test.js` test.

This test uses `@salesforce/core/lib/testSetup` which I hadn't seen mentioned anywhere else before:
```
  test
    .withOrg({ username: 'test@org.com' }, true)
    .do(ctx => {
      $$.SANDBOX.stub(StreamingClient, 'init').callsFake(async options => {
        return {
          handshake: async () => StreamingConnectionState.CONNECTED,
          subscribe: async () => options.streamProcessor({payload: { Message__c: 'test message'}, event: {replayId: 20}})
        };
      });
    })
```
Again, I can't really tell what it does. What does `$$.SANDBOX.stub` do? The example stubs/fakes a static function. How would I fake a non-static one? 

### Shane McLaughlin's plugin

Seems to take a completely different approach: the tests don't use `test.withOrg()` but what seems to be **jest** in combination with his own test framework `@mshanemc/plugin-helpers/dist/testutils`:
```
        beforeAll(async () => {
            await fs.remove(testProjectName);
            await exec(`sfdx force:project:create -n ${testProjectName}`);
            await Promise.all([testutils.orgCreate(testProjectName), fs.ensureDir(`${testProjectName}/force-app/main/default/permissionsets`)]);

            // convert to xml and write out the file
            const xml = jsToXml.parse('PermissionSet', permsetMeta, standardOptions);
            await fs.writeFile(`${testProjectName}/force-app/main/default/permissionsets/${permsetName}.permissionset-meta.xml`, xml);
            await exec(`sfdx force:source:push`, { cwd: testProjectName });
        });
```

 Obviously he would be the best person to ask why he did that, but again it's yet another way of testing a plugin. Perhaps he went this route because he also couldn't figure out how the "standard" test framework was supposed to work.

So.... I really don't hope this comes across as a big whine. It's just a bit of frustration with seeing how awesome SFDX plugins can be but just really struggling to actually write one because there is so little documentation on almost everything.

Maybe it's because I come from a Java background and am looking at Javascript/Typescript through a Java lens. But even then I do think more documentation would benefit even people that do have a Javascript background.

- Is there documentation I've missed? Where can I find it?
- Is there some documented best practice around testing sfdx plugins that I can follow, along with explanations of what's actually happening behind the scenes?

I'm aware this is your personal repo and for all I know you don't work for Salesforce anymore, so do let me know what a better place is to post this question!

Thanks!!
Frans

**Comment by amphro** [comment]
Comprehensive questions. Unfortunately, you are right that it is not well documented. I don't have time to write a comprehensive response, but I wanted to at least give you something before I forget to respond entirely.

The generated plugin's test was created more than a few years ago and hasn't received much love since then. The goal was to provide an easier way to **mock** an org and project so plugin authors could write command level unit tests without knowing how to mock out the `@salesforce/core` library. Since oclif uses [fancy test](https://github.com/oclif/fancy-test) for it's tests, helpers like `withOrg` were provided which needed something like [test setup](https://github.com/forcedotcom/sfdx-core#using-testsetup). The best way is to just look at the code [here](https://github.com/forcedotcom/cli-packages/blob/main/packages/command/src/test/index.ts) and [here](https://github.com/forcedotcom/sfdx-core/blob/main/src/testSetup.ts). 

This repo was created right around when all the `withOrg` stuff was, so it follows that pattern.

With that said, I don't love fancy tests and a lot of others don't. It also locks you into mocha, which some developers just don't want to do. Helpers like `withOrg` only support unit tests, which some developers need more. An example of this is Shane, so they do their own solution.

For plugin testkit, it is really new. As per the README, it is a way to "writing NUTs (non-unit-tests), like integration, smoke, and e2e style testing". Shane and the Salesforce CLI team spend a lot of time trying to make it easy to use create integration test against real orgs. The [readme](https://github.com/salesforcecli/cli-plugins-testkit) is really the best place to learn more, and if there isn't information or examples you are looking for, file an issue there.

The best place for this sort of feedback and request for more documentation and examples should go https://github.com/forcedotcom/cli - the team tries to engage and respond as much as possible.

**Comment by fransflippo** [comment]
Thank you so much for your reply, Thomas. This kind of context helps a lot to make more sense of what's out there and how it's related.

I'll check the the testkit readme and the forcedotcom/cli GitHub repo you mentioned and take it from there.

Thanks again!

**Comment by fransflippo** [comment]
And I somehow completely missed https://github.com/forcedotcom/sfdx-core#using-testsetup . Lots of info I was looking for there, thanks!

So to summarize:
- to unit test your plugin and mock out the Salesforce core components, including mocking out the connection to a scratch org, use the `withOrg` helper (as generated by the plugin generator) along with [testSetup](https://github.com/forcedotcom/sfdx-core#using-testsetup).
- to end-to-end integration test your plugin against a real scratch org, use the plugins-testkit
- to test helpers in your plugins in an isolated manner, use your preferred testing framework (e.g. mocha and chai) along with sinon to stub out dependencies if needed
